name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  deploy:
    name: Deploy HTML Docker App to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/hello-html

    - name: Deploy Docker container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd hello-html
          echo '
          FROM nginx:alpine
          COPY index.html /usr/share/nginx/html/index.html
          ' > Dockerfile

          docker stop hello-html || true && docker rm hello-html || true
          docker build -t hello-html .
          docker run -d -p 8080:80 --name hello-html hello-html
        EOF
